- name: Deploy Project Artifacts to Vercel
id: vercel
env:
  META_TAG:
    ${{ steps.hash_branch.outputs.digest }}-${{ github.run_number }}-${{
    github.run_attempt}}
run: |
  vercel --version
  vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
  vercel build --token=$VERCEL_TOKEN
  vercel deploy --prebuilt --archive=tgz --token=$VERCEL_TOKEN --meta base_hash=${{ env.META_TAG }} --name ${{ github.head_ref }}

  vercel ls --token=$VERCEL_TOKEN --meta base_hash=${{ env.META_TAG }} &> vercel-output
  url=$(cat vercel-output | grep http | awk '{print $2}')
  echo "New preview URL: $url"
  echo "META_TAG=$META_TAG"
  echo "preview_url=$url" >> "$GITHUB_OUTPUT"