name: Release

on:
  workflow_dispatch:
    branches:
      - main
    # inputs: # Could be used to manually specify the release tag
    #   tag:
    #     description: "The tag to release (Format: v*.*.*)"
    #     required: true

jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{secrets.github_token}}
          output-file: "false"

      - name: Create Release # This action will create the actual release
        uses: actions/create-release@v1
        if: ${{steps.changelog.outputs.skipped == 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
