name: Release

on:
  workflow_dispatch:
    branches:
      - main
    inputs: # Could be used to manually specify the release tag
      sprint_number:
        description: "The current sprint number"
        required: true
        type: choice
        options:
          - "Sprint 1"
          - "Sprint 2"
          - "Sprint 3"
          - "Sprint 4"

permissions:
  contents: write

jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{secrets.SKIP_BRANCH_PROTECTION_TOKEN}}

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          output-file: "false"

      - name: Create Release # This action will create the actual release
        uses: actions/create-release@v1
        if: ${{steps.changelog.outputs.skipped == 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: |
            # Release for **${{inputs.sprint_number}}**
            ${{ steps.changelog.outputs.clean_changelog }}
