name: Run Tests (production)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Test:
    runs-on: ubuntu-latest
    environment: Develop
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        id: vercel_pull
        run: |
          vercel pull --yes --environment=preview --git-branch=develop
          --token=${{ secrets.VERCEL_TOKEN }} 
          source .vercel/.env.DATABASE_URL
          source .vercel/.env.DIRECT_DATABASE_URL 
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV 
          echo "DIRECT_DATABASE_URL=$DIRECT_DATABASE_URL" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test

      - name: Lint
        run: |
          npm run lint
          npm run prisma:validate
